language: python

dist: xenial

python:
  - "3.8"

install:
  - echo "HI"

before_script:
  - echo "before script"

script:
  - echo "script"

env:
  - FILENAME=/tmp/travistest/travis.tar
    DOCKER_PLATFORM=linux/386,linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 
    TARGET_IMAGE=delfick/travistest

before_deploy:
  - pip install venvstarter
  - mkdir /tmp/travistest
  - ./docker/harpoon get_docker_context travistest 

  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use

  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  on:
    tags: true

  script: >-
    cd /tmp/travistest
    && tar xf travis.tar
    && docker buildx build --progress plain --platform $DOCKER_PLATFORM --push -t ${TARGET_IMAGE}:${TRAVIS_TAG} -t ${TARGET_IMAGE}:latest .
